web:
  last_stable_version: '1.0'
  repository_url: git@bitbucket.org:drdplusinfo/bestiary-dm-web.git
  menu_position_fixed: false
  show_home_button: true
  protected_access: false
  eshop_url: https://obchod.altar.cz/
  name: DrD+ PJ bestiÃ¡Å™
  title_smiley: ğŸ€
google:
  analytics_id: UA-121206931-5