web:
  menu_position_fixed: false
  show_home_button: true
  protected_access: false
  eshop_url: https://obchod.altar.cz/drd-prirucka-pj-everze-p-1012.html
  name: DrD+ PJ bestiÃ¡Å™
  title_smiley: ğŸ€
google:
  analytics_id: UA-121206931-5